/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "CloudToDeviceProperties.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

CloudToDeviceProperties::CloudToDeviceProperties()
{
    m_MaxDeliveryCount = 0;
    m_MaxDeliveryCountIsSet = false;
    m_DefaultTtlAsIso8601 = U("");
    m_DefaultTtlAsIso8601IsSet = false;
    m_FeedbackIsSet = false;
}

CloudToDeviceProperties::~CloudToDeviceProperties()
{
}

void CloudToDeviceProperties::validate()
{
    // TODO: implement validation
}

web::json::value CloudToDeviceProperties::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_MaxDeliveryCountIsSet)
    {
        val[U("maxDeliveryCount")] = ModelBase::toJson(m_MaxDeliveryCount);
    }
    if(m_DefaultTtlAsIso8601IsSet)
    {
        val[U("defaultTtlAsIso8601")] = ModelBase::toJson(m_DefaultTtlAsIso8601);
    }
    if(m_FeedbackIsSet)
    {
        val[U("feedback")] = ModelBase::toJson(m_Feedback);
    }

    return val;
}

void CloudToDeviceProperties::fromJson(web::json::value& val)
{
    if(val.has_field(U("maxDeliveryCount")))
    {
        setMaxDeliveryCount(ModelBase::int32_tFromJson(val[U("maxDeliveryCount")]));
    }
    if(val.has_field(U("defaultTtlAsIso8601")))
    {
        setDefaultTtlAsIso8601(ModelBase::stringFromJson(val[U("defaultTtlAsIso8601")]));
    }
    if(val.has_field(U("feedback")))
    {
        if(!val[U("feedback")].is_null())
        {
            std::shared_ptr<FeedbackProperties> newItem(new FeedbackProperties());
            newItem->fromJson(val[U("feedback")]);
            setFeedback( newItem );
        }
    }
}

void CloudToDeviceProperties::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_MaxDeliveryCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("maxDeliveryCount"), m_MaxDeliveryCount));
    }
    if(m_DefaultTtlAsIso8601IsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("defaultTtlAsIso8601"), m_DefaultTtlAsIso8601));
        
    }
    if(m_FeedbackIsSet)
    {
        if (m_Feedback.get())
        {
            m_Feedback->toMultipart(multipart, U("feedback."));
        }
        
    }
}

void CloudToDeviceProperties::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("maxDeliveryCount")))
    {
        setMaxDeliveryCount(ModelBase::int32_tFromHttpContent(multipart->getContent(U("maxDeliveryCount"))));
    }
    if(multipart->hasContent(U("defaultTtlAsIso8601")))
    {
        setDefaultTtlAsIso8601(ModelBase::stringFromHttpContent(multipart->getContent(U("defaultTtlAsIso8601"))));
    }
    if(multipart->hasContent(U("feedback")))
    {
        if(multipart->hasContent(U("feedback")))
        {
            std::shared_ptr<FeedbackProperties> newItem(new FeedbackProperties());
            newItem->fromMultiPart(multipart, U("feedback."));
            setFeedback( newItem );
        }
    }
}

int32_t CloudToDeviceProperties::getMaxDeliveryCount() const
{
    return m_MaxDeliveryCount;
}


void CloudToDeviceProperties::setMaxDeliveryCount(int32_t value)
{
    m_MaxDeliveryCount = value;
    m_MaxDeliveryCountIsSet = true;
}
bool CloudToDeviceProperties::maxDeliveryCountIsSet() const
{
    return m_MaxDeliveryCountIsSet;
}

void CloudToDeviceProperties::unsetMaxDeliveryCount()
{
    m_MaxDeliveryCountIsSet = false;
}

utility::string_t CloudToDeviceProperties::getDefaultTtlAsIso8601() const
{
    return m_DefaultTtlAsIso8601;
}


void CloudToDeviceProperties::setDefaultTtlAsIso8601(utility::string_t value)
{
    m_DefaultTtlAsIso8601 = value;
    m_DefaultTtlAsIso8601IsSet = true;
}
bool CloudToDeviceProperties::defaultTtlAsIso8601IsSet() const
{
    return m_DefaultTtlAsIso8601IsSet;
}

void CloudToDeviceProperties::unsetDefaultTtlAsIso8601()
{
    m_DefaultTtlAsIso8601IsSet = false;
}

std::shared_ptr<FeedbackProperties> CloudToDeviceProperties::getFeedback() const
{
    return m_Feedback;
}


void CloudToDeviceProperties::setFeedback(std::shared_ptr<FeedbackProperties> value)
{
    m_Feedback = value;
    m_FeedbackIsSet = true;
}
bool CloudToDeviceProperties::feedbackIsSet() const
{
    return m_FeedbackIsSet;
}

void CloudToDeviceProperties::unsetFeedback()
{
    m_FeedbackIsSet = false;
}

}
}
}
}

