/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ImportDevicesRequest.h
 *
 * Use to provide parameters when requesting an import of all devices in the hub.
 */

#ifndef ImportDevicesRequest_H_
#define ImportDevicesRequest_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Use to provide parameters when requesting an import of all devices in the hub.
/// </summary>
class  ImportDevicesRequest
    : public ModelBase
{
public:
    ImportDevicesRequest();
    virtual ~ImportDevicesRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ImportDevicesRequest members

    /// <summary>
    /// The input blob container URI.
    /// </summary>
    utility::string_t getInputBlobContainerUri() const;
    void setInputBlobContainerUri(utility::string_t value);
        /// <summary>
    /// The output blob container URI.
    /// </summary>
    utility::string_t getOutputBlobContainerUri() const;
    void setOutputBlobContainerUri(utility::string_t value);
    
protected:
    utility::string_t m_InputBlobContainerUri;
        utility::string_t m_OutputBlobContainerUri;
    };

}
}
}
}

#endif /* ImportDevicesRequest_H_ */
