/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_7_value.h
 *
 * Quota metrics properties.
 */

#ifndef Inline_response_200_7_value_H_
#define Inline_response_200_7_value_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Quota metrics properties.
/// </summary>
class  Inline_response_200_7_value
    : public ModelBase
{
public:
    Inline_response_200_7_value();
    virtual ~Inline_response_200_7_value();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Inline_response_200_7_value members

    /// <summary>
    /// The name of the quota metric.
    /// </summary>
    utility::string_t getName() const;
    void setName(utility::string_t value);
    bool NameIsSet() const;
    void unsetName();
    /// <summary>
    /// The current value for the quota metric.
    /// </summary>
    int64_t getCurrentValue() const;
    void setCurrentValue(int64_t value);
    bool CurrentValueIsSet() const;
    void unsetCurrentValue();
    /// <summary>
    /// The maximum value of the quota metric.
    /// </summary>
    int64_t getMaxValue() const;
    void setMaxValue(int64_t value);
    bool MaxValueIsSet() const;
    void unsetMaxValue();

protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
int64_t m_CurrentValue;
    bool m_CurrentValueIsSet;
int64_t m_MaxValue;
    bool m_MaxValueIsSet;
};

}
}
}
}

#endif /* Inline_response_200_7_value_H_ */
