/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Inline_response_200_7_value.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Inline_response_200_7_value::Inline_response_200_7_value()
{
    m_Name = U("");
    m_NameIsSet = false;
    m_CurrentValue = 0;
    m_CurrentValueIsSet = false;
    m_MaxValue = 0;
    m_MaxValueIsSet = false;
    
}

Inline_response_200_7_value::~Inline_response_200_7_value()
{
}

void Inline_response_200_7_value::validate()
{
    // TODO: implement validation
}

web::json::value Inline_response_200_7_value::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_NameIsSet)
    {
        val[U("Name")] = ModelBase::toJson(m_Name);
    }
    if(m_CurrentValueIsSet)
    {
        val[U("CurrentValue")] = ModelBase::toJson(m_CurrentValue);
    }
    if(m_MaxValueIsSet)
    {
        val[U("MaxValue")] = ModelBase::toJson(m_MaxValue);
    }
    

    return val;
}

void Inline_response_200_7_value::fromJson(web::json::value& val)
{
    if(val.has_field(U("Name")))
    {
        setName(ModelBase::stringFromJson(val[U("Name")]));
        
    }
    if(val.has_field(U("CurrentValue")))
    {
        setCurrentValue(ModelBase::int64_tFromJson(val[U("CurrentValue")]));
    }
    if(val.has_field(U("MaxValue")))
    {
        setMaxValue(ModelBase::int64_tFromJson(val[U("MaxValue")]));
    }
    
}

void Inline_response_200_7_value::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("Name"), m_Name));
        
    }
    if(m_CurrentValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("CurrentValue"), m_CurrentValue));
    }
    if(m_MaxValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("MaxValue"), m_MaxValue));
    }
    
}

void Inline_response_200_7_value::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("Name")))
    {
        setName(ModelBase::stringFromHttpContent(multipart->getContent(U("Name"))));
        
    }
    if(multipart->hasContent(U("CurrentValue")))
    {
        setCurrentValue(ModelBase::int64_tFromHttpContent(multipart->getContent(U("CurrentValue"))));
    }
    if(multipart->hasContent(U("MaxValue")))
    {
        setMaxValue(ModelBase::int64_tFromHttpContent(multipart->getContent(U("MaxValue"))));
    }
    
}


utility::string_t Inline_response_200_7_value::getName() const
{
    return m_Name;
}
void Inline_response_200_7_value::setName(utility::string_t value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool Inline_response_200_7_value::NameIsSet() const
{
    return m_NameIsSet;
}
void Inline_response_200_7_value::unsetName()
{
    m_NameIsSet = false;
}
int64_t Inline_response_200_7_value::getCurrentValue() const
{
    return m_CurrentValue;
}
void Inline_response_200_7_value::setCurrentValue(int64_t value)
{
    m_CurrentValue = value;
    m_CurrentValueIsSet = true;
}
bool Inline_response_200_7_value::CurrentValueIsSet() const
{
    return m_CurrentValueIsSet;
}
void Inline_response_200_7_value::unsetCurrentValue()
{
    m_CurrentValueIsSet = false;
}
int64_t Inline_response_200_7_value::getMaxValue() const
{
    return m_MaxValue;
}
void Inline_response_200_7_value::setMaxValue(int64_t value)
{
    m_MaxValue = value;
    m_MaxValueIsSet = true;
}
bool Inline_response_200_7_value::MaxValueIsSet() const
{
    return m_MaxValueIsSet;
}
void Inline_response_200_7_value::unsetMaxValue()
{
    m_MaxValueIsSet = false;
}

}
}
}
}

