/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Inline_response_200_5.h
 *
 * The properties of the EventHubConsumerGroupInfo object.
 */

#ifndef Inline_response_200_5_H_
#define Inline_response_200_5_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// The properties of the EventHubConsumerGroupInfo object.
/// </summary>
class  Inline_response_200_5
    : public ModelBase
{
public:
    Inline_response_200_5();
    virtual ~Inline_response_200_5();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Inline_response_200_5 members

    /// <summary>
    /// The tags.
    /// </summary>
    std::map<utility::string_t, utility::string_t>& getTags();
    bool tagsIsSet() const;
    void unsetTags();
    /// <summary>
    /// The Event Hub-compatible consumer group identifier.
    /// </summary>
    utility::string_t getId() const;
    void setId(utility::string_t value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// The Event Hub-compatible consumer group name.
    /// </summary>
    utility::string_t getName() const;
    void setName(utility::string_t value);
    bool nameIsSet() const;
    void unsetName();

protected:
    std::map<utility::string_t, utility::string_t> m_Tags;
    bool m_TagsIsSet;
utility::string_t m_Id;
    bool m_IdIsSet;
utility::string_t m_Name;
    bool m_NameIsSet;
};

}
}
}
}

#endif /* Inline_response_200_5_H_ */
