/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubSkuDescription.h
 *
 * SKU properties.
 */

#ifndef IotHubSkuDescription_H_
#define IotHubSkuDescription_H_


#include "ModelBase.h"

#include "IotHubCapacity.h"
#include <cpprest/details/basic_types.h>
#include "IotHubSkuInfo.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// SKU properties.
/// </summary>
class  IotHubSkuDescription
    : public ModelBase
{
public:
    IotHubSkuDescription();
    virtual ~IotHubSkuDescription();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubSkuDescription members

    /// <summary>
    /// The type of the resource.
    /// </summary>
    utility::string_t getResourceType() const;
    bool resourceTypeIsSet() const;
    void unsetResourceType();
    void setResourceType(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<IotHubSkuInfo> getSku() const;
        void setSku(std::shared_ptr<IotHubSkuInfo> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<IotHubCapacity> getCapacity() const;
        void setCapacity(std::shared_ptr<IotHubCapacity> value);

protected:
    utility::string_t m_ResourceType;
    bool m_ResourceTypeIsSet;
    std::shared_ptr<IotHubSkuInfo> m_Sku;
        std::shared_ptr<IotHubCapacity> m_Capacity;
    };

}
}
}
}

#endif /* IotHubSkuDescription_H_ */
