/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubDescription.h
 *
 * The description of the IoT hub.
 */

#ifndef IotHubDescription_H_
#define IotHubDescription_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>
#include "Resource.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// The description of the IoT hub.
/// </summary>
class  IotHubDescription
    : public ModelBase
{
public:
    IotHubDescription();
    virtual ~IotHubDescription();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubDescription members

    /// <summary>
    /// The resource identifier.
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(utility::string_t value);
    /// <summary>
    /// The resource name.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(utility::string_t value);
    /// <summary>
    /// The resource type.
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(utility::string_t value);
    /// <summary>
    /// The resource location.
    /// </summary>
    utility::string_t getLocation() const;
        void setLocation(utility::string_t value);
    /// <summary>
    /// The resource tags.
    /// </summary>
    std::map<utility::string_t, utility::string_t>& getTags();
    bool tagsIsSet() const;
    void unsetTags();
    void setTags(std::map<utility::string_t, utility::string_t> value);

protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Type;
    bool m_TypeIsSet;
    utility::string_t m_Location;
        std::map<utility::string_t, utility::string_t> m_Tags;
    bool m_TagsIsSet;
};

}
}
}
}

#endif /* IotHubDescription_H_ */
