/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubProperties_cloudToDevice.h
 *
 * The IoT hub cloud-to-device messaging properties.
 */

#ifndef IotHubProperties_cloudToDevice_H_
#define IotHubProperties_cloudToDevice_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "IotHubProperties_cloudToDevice_feedback.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// The IoT hub cloud-to-device messaging properties.
/// </summary>
class  IotHubProperties_cloudToDevice
    : public ModelBase
{
public:
    IotHubProperties_cloudToDevice();
    virtual ~IotHubProperties_cloudToDevice();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubProperties_cloudToDevice members

    /// <summary>
    /// The max delivery count for cloud-to-device messages in the device queue. See: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging#cloud-to-device-messages.
    /// </summary>
    int32_t getMaxDeliveryCount() const;
    void setMaxDeliveryCount(int32_t value);
    bool maxDeliveryCountIsSet() const;
    void unsetMaxDeliveryCount();
    /// <summary>
    /// The default time to live for cloud-to-device messages in the device queue. See: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging#cloud-to-device-messages.
    /// </summary>
    utility::string_t getDefaultTtlAsIso8601() const;
    void setDefaultTtlAsIso8601(utility::string_t value);
    bool defaultTtlAsIso8601IsSet() const;
    void unsetDefaultTtlAsIso8601();
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<IotHubProperties_cloudToDevice_feedback> getFeedback() const;
    void setFeedback(std::shared_ptr<IotHubProperties_cloudToDevice_feedback> value);
    bool feedbackIsSet() const;
    void unsetFeedback();

protected:
    int32_t m_MaxDeliveryCount;
    bool m_MaxDeliveryCountIsSet;
utility::string_t m_DefaultTtlAsIso8601;
    bool m_DefaultTtlAsIso8601IsSet;
std::shared_ptr<IotHubProperties_cloudToDevice_feedback> m_Feedback;
    bool m_FeedbackIsSet;
};

}
}
}
}

#endif /* IotHubProperties_cloudToDevice_H_ */
