/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubQuotaMetricInfoListResult.h
 *
 * The JSON-serialized array of IotHubQuotaMetricInfo objects with a next link.
 */

#ifndef IotHubQuotaMetricInfoListResult_H_
#define IotHubQuotaMetricInfoListResult_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>
#include "IotHubQuotaMetricInfo.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// The JSON-serialized array of IotHubQuotaMetricInfo objects with a next link.
/// </summary>
class  IotHubQuotaMetricInfoListResult
    : public ModelBase
{
public:
    IotHubQuotaMetricInfoListResult();
    virtual ~IotHubQuotaMetricInfoListResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubQuotaMetricInfoListResult members

    /// <summary>
    /// The array of quota metrics objects.
    /// </summary>
    std::vector<std::shared_ptr<IotHubQuotaMetricInfo>>& getValue();
    bool valueIsSet() const;
    void unsetValue();
    /// <summary>
    /// The next link.
    /// </summary>
    utility::string_t getNextLink() const;
    void setNextLink(utility::string_t value);
    bool nextLinkIsSet() const;
    void unsetNextLink();

protected:
    std::vector<std::shared_ptr<IotHubQuotaMetricInfo>> m_Value;
    bool m_ValueIsSet;
    utility::string_t m_NextLink;
    bool m_NextLinkIsSet;
};

}
}
}
}

#endif /* IotHubQuotaMetricInfoListResult_H_ */
