/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubQuotaMetricInfo.h
 *
 * Quota metrics properties.
 */

#ifndef IotHubQuotaMetricInfo_H_
#define IotHubQuotaMetricInfo_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Quota metrics properties.
/// </summary>
class  IotHubQuotaMetricInfo
    : public ModelBase
{
public:
    IotHubQuotaMetricInfo();
    virtual ~IotHubQuotaMetricInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubQuotaMetricInfo members

    /// <summary>
    /// The name of the quota metric.
    /// </summary>
    utility::string_t getName() const;
    bool NameIsSet() const;
    void unsetName();
    void setName(utility::string_t value);
    /// <summary>
    /// The current value for the quota metric.
    /// </summary>
    int64_t getCurrentValue() const;
    bool CurrentValueIsSet() const;
    void unsetCurrentValue();
    void setCurrentValue(int64_t value);
    /// <summary>
    /// The maximum value of the quota metric.
    /// </summary>
    int64_t getMaxValue() const;
    bool MaxValueIsSet() const;
    void unsetMaxValue();
    void setMaxValue(int64_t value);

protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
    int64_t m_CurrentValue;
    bool m_CurrentValueIsSet;
    int64_t m_MaxValue;
    bool m_MaxValueIsSet;
};

}
}
}
}

#endif /* IotHubQuotaMetricInfo_H_ */
