/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubDescriptionListResult.h
 *
 * The JSON-serialized array of IotHubDescription objects with a next link.
 */

#ifndef IotHubDescriptionListResult_H_
#define IotHubDescriptionListResult_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>
#include "IotHubDescription.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// The JSON-serialized array of IotHubDescription objects with a next link.
/// </summary>
class  IotHubDescriptionListResult
    : public ModelBase
{
public:
    IotHubDescriptionListResult();
    virtual ~IotHubDescriptionListResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubDescriptionListResult members

    /// <summary>
    /// The array of IotHubDescription objects.
    /// </summary>
    std::vector<std::shared_ptr<IotHubDescription>>& getValue();
    bool valueIsSet() const;
    void unsetValue();
    void setValue(std::vector<std::shared_ptr<IotHubDescription>> value);
    /// <summary>
    /// The next link.
    /// </summary>
    utility::string_t getNextLink() const;
    bool nextLinkIsSet() const;
    void unsetNextLink();
    void setNextLink(utility::string_t value);

protected:
    std::vector<std::shared_ptr<IotHubDescription>> m_Value;
    bool m_ValueIsSet;
    utility::string_t m_NextLink;
    bool m_NextLinkIsSet;
};

}
}
}
}

#endif /* IotHubDescriptionListResult_H_ */
