/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IotHubProperties_eventHubEndpoints.h
 *
 * The properties of the provisioned Event Hub-compatible endpoint used by the IoT hub.
 */

#ifndef IotHubProperties_eventHubEndpoints_H_
#define IotHubProperties_eventHubEndpoints_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// The properties of the provisioned Event Hub-compatible endpoint used by the IoT hub.
/// </summary>
class  IotHubProperties_eventHubEndpoints
    : public ModelBase
{
public:
    IotHubProperties_eventHubEndpoints();
    virtual ~IotHubProperties_eventHubEndpoints();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IotHubProperties_eventHubEndpoints members

    /// <summary>
    /// The retention time for device-to-cloud messages in days. See: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging#device-to-cloud-messages
    /// </summary>
    int64_t getRetentionTimeInDays() const;
    void setRetentionTimeInDays(int64_t value);
    bool retentionTimeInDaysIsSet() const;
    void unsetRetentionTimeInDays();
    /// <summary>
    /// The number of paritions for receiving device-to-cloud messages in the Event Hub-compatible endpoint. See: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-messaging#device-to-cloud-messages.
    /// </summary>
    int32_t getPartitionCount() const;
    void setPartitionCount(int32_t value);
    bool partitionCountIsSet() const;
    void unsetPartitionCount();
    /// <summary>
    /// The partition ids in the Event Hub-compatible endpoint.
    /// </summary>
    std::vector<utility::string_t>& getPartitionIds();
    bool partitionIdsIsSet() const;
    void unsetPartitionIds();
    /// <summary>
    /// The Event Hub-compatible name.
    /// </summary>
    utility::string_t getPath() const;
    void setPath(utility::string_t value);
    bool pathIsSet() const;
    void unsetPath();
    /// <summary>
    /// The Event Hub-compatible endpoint.
    /// </summary>
    utility::string_t getEndpoint() const;
    void setEndpoint(utility::string_t value);
    bool endpointIsSet() const;
    void unsetEndpoint();

protected:
    int64_t m_RetentionTimeInDays;
    bool m_RetentionTimeInDaysIsSet;
int32_t m_PartitionCount;
    bool m_PartitionCountIsSet;
std::vector<utility::string_t> m_PartitionIds;
    bool m_PartitionIdsIsSet;
utility::string_t m_Path;
    bool m_PathIsSet;
utility::string_t m_Endpoint;
    bool m_EndpointIsSet;
};

}
}
}
}

#endif /* IotHubProperties_eventHubEndpoints_H_ */
