/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "OperationInputs.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

OperationInputs::OperationInputs()
{
    m_Name = U("");
    
}

OperationInputs::~OperationInputs()
{
}

void OperationInputs::validate()
{
    // TODO: implement validation
}

web::json::value OperationInputs::toJson() const
{
    web::json::value val = web::json::value::object();

    val[U("Name")] = ModelBase::toJson(m_Name);
    

    return val;
}

void OperationInputs::fromJson(web::json::value& val)
{
    setName(ModelBase::stringFromJson(val[U("Name")]));
    
}

void OperationInputs::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + U("Name"), m_Name));
    
}

void OperationInputs::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    setName(ModelBase::stringFromHttpContent(multipart->getContent(U("Name"))));
    
}


utility::string_t OperationInputs::getName() const
{
    return m_Name;
}
void OperationInputs::setName(utility::string_t value)
{
    m_Name = value;
    
}

}
}
}
}

