/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * OperationInputs.h
 *
 * Input values.
 */

#ifndef OperationInputs_H_
#define OperationInputs_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Input values.
/// </summary>
class  OperationInputs
    : public ModelBase
{
public:
    OperationInputs();
    virtual ~OperationInputs();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// OperationInputs members

    /// <summary>
    /// The name of the IoT hub to check.
    /// </summary>
    utility::string_t getName() const;
    void setName(utility::string_t value);
    
protected:
    utility::string_t m_Name;
    };

}
}
}
}

#endif /* OperationInputs_H_ */
