/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DELETEApi.h
 *
 * 
 */

#ifndef DELETEApi_H_
#define DELETEApi_H_


#include "ApiClient.h"

#include "Inline_response_200.h"
#include "Inline_response_default.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  DELETEApi
{
public:
    DELETEApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~DELETEApi();
    /// <summary>
    /// Delete an IoT hub.
    /// </summary>
    /// <remarks>
    /// Delete an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub to delete.</param>
    pplx::task<std::shared_ptr<Inline_response_200>> iotHubResourceDelete(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName);
    /// <summary>
    /// Delete a consumer group from an Event Hub-compatible endpoint in an IoT hub.
    /// </summary>
    /// <remarks>
    /// Delete a consumer group from an Event Hub-compatible endpoint in an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>/// <param name="eventHubEndpointName">The name of the Event Hub-compatible endpoint in the IoT hub.</param>/// <param name="name">The name of the consumer group to delete.</param>
    pplx::task<void> iotHubResourceDeleteEventHubConsumerGroup(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName, utility::string_t eventHubEndpointName, utility::string_t name);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* DELETEApi_H_ */

