/**
 * iotHubClient
 * Use this API to manage the IoT hubs in your Azure subscription.
 *
 * OpenAPI spec version: 2017-01-19
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * GETApi.h
 *
 * 
 */

#ifndef GETApi_H_
#define GETApi_H_


#include "ApiClient.h"

#include "Inline_response_200.h"
#include "Inline_response_200_1.h"
#include "Inline_response_200_2.h"
#include "Inline_response_200_3.h"
#include "Inline_response_200_4.h"
#include "Inline_response_200_5.h"
#include "Inline_response_200_6.h"
#include "Inline_response_200_6_value.h"
#include "Inline_response_200_7.h"
#include "Inline_response_default.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  GETApi
{
public:
    GETApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~GETApi();
    /// <summary>
    /// Get the non-security related metadata of an IoT hub.
    /// </summary>
    /// <remarks>
    /// Get the non-security related metadata of an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>
    pplx::task<std::shared_ptr<Inline_response_200>> iotHubResourceGet(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName);
    /// <summary>
    /// Get a consumer group from the Event Hub-compatible device-to-cloud endpoint for an IoT hub.
    /// </summary>
    /// <remarks>
    /// Get a consumer group from the Event Hub-compatible device-to-cloud endpoint for an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>/// <param name="eventHubEndpointName">The name of the Event Hub-compatible endpoint in the IoT hub.</param>/// <param name="name">The name of the consumer group to retrieve.</param>
    pplx::task<std::shared_ptr<Inline_response_200_5>> iotHubResourceGetEventHubConsumerGroup(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName, utility::string_t eventHubEndpointName, utility::string_t name);
    /// <summary>
    /// Get the details of a job from an IoT hub. For more information, see: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry.
    /// </summary>
    /// <remarks>
    /// Get the details of a job from an IoT hub. For more information, see: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>/// <param name="jobId">The job identifier.</param>
    pplx::task<std::shared_ptr<Inline_response_200_6_value>> iotHubResourceGetJob(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName, utility::string_t jobId);
    /// <summary>
    /// Get the quota metrics for an IoT hub.
    /// </summary>
    /// <remarks>
    /// Get the quota metrics for an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>
    pplx::task<std::shared_ptr<Inline_response_200_7>> iotHubResourceGetQuotaMetrics(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName);
    /// <summary>
    /// Get the statistics from an IoT hub.
    /// </summary>
    /// <remarks>
    /// Get the statistics from an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>
    pplx::task<std::shared_ptr<Inline_response_200_2>> iotHubResourceGetStats(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName);
    /// <summary>
    /// Get the list of valid SKUs for an IoT hub.
    /// </summary>
    /// <remarks>
    /// Get the list of valid SKUs for an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>
    pplx::task<std::shared_ptr<Inline_response_200_3>> iotHubResourceGetValidSkus(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName);
    /// <summary>
    /// Get all the IoT hubs in a resource group.
    /// </summary>
    /// <remarks>
    /// Get all the IoT hubs in a resource group.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hubs.</param>
    pplx::task<std::shared_ptr<Inline_response_200_1>> iotHubResourceListByResourceGroup(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName);
    /// <summary>
    /// Get all the IoT hubs in a subscription.
    /// </summary>
    /// <remarks>
    /// Get all the IoT hubs in a subscription.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>
    pplx::task<std::shared_ptr<Inline_response_200_1>> iotHubResourceListBySubscription(utility::string_t apiVersion, utility::string_t subscriptionId);
    /// <summary>
    /// Get a list of the consumer groups in the Event Hub-compatible device-to-cloud endpoint in an IoT hub.
    /// </summary>
    /// <remarks>
    /// Get a list of the consumer groups in the Event Hub-compatible device-to-cloud endpoint in an IoT hub.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>/// <param name="eventHubEndpointName">The name of the Event Hub-compatible endpoint.</param>
    pplx::task<std::shared_ptr<Inline_response_200_4>> iotHubResourceListEventHubConsumerGroups(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName, utility::string_t eventHubEndpointName);
    /// <summary>
    /// Get a list of all the jobs in an IoT hub. For more information, see: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry.
    /// </summary>
    /// <remarks>
    /// Get a list of all the jobs in an IoT hub. For more information, see: https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry.
    /// </remarks>
    /// <param name="apiVersion">The version of the API.</param>/// <param name="subscriptionId">The subscription identifier.</param>/// <param name="resourceGroupName">The name of the resource group that contains the IoT hub.</param>/// <param name="resourceName">The name of the IoT hub.</param>
    pplx::task<std::shared_ptr<Inline_response_200_6>> iotHubResourceListJobs(utility::string_t apiVersion, utility::string_t subscriptionId, utility::string_t resourceGroupName, utility::string_t resourceName);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* GETApi_H_ */

